// Array to store the sequence generated by the game
let gamePatterns = [];

// Array to store the sequence clicked by the user
let userClickedPattern = [];

// Boolean to track whether the game has started or not
let start = false;

// Current level of the game
let level = 0;

// Available button colors
let btnColors = ["red", "green", "blue", "yellow"];

// Detect a keypress to start the game
$(document).keypress(() => {
  if (!start) {
    $("#level-title").text("Level " + level); // Show current level
    nextSequence(); // Start the game with first sequence
    start = true; // Mark game as started
  }
});

// Function to generate the next sequence
function nextSequence() {
  userClickedPattern = []; // Reset user's pattern for this round
  level++; // Increase level
  $("#level-title").text("Level " + level); // Update heading

  // Pick a random color
  let randomNumber = Math.floor(Math.random() * 4);
  let randomChosenColor = btnColors[randomNumber];
  gamePatterns.push(randomChosenColor); // Add to game sequence

  // Animate the chosen button
  $("#" + randomChosenColor)
    .fadeIn(100)
    .fadeOut(100)
    .fadeIn(100);

  // Play sound for chosen color
  playSound(randomChosenColor);
}

// Detect when a user clicks a button
$(".btn").click(function() {
  let userChosenColor = $(this).attr("id"); // Get clicked color
  userClickedPattern.push(userChosenColor); // Add to user sequence

  playSound(userChosenColor); // Play sound
  animatePress(userChosenColor); // Add button animation

  // Check the user's answer
  checkAnswer(userClickedPattern.length - 1);
});

// Function to check the user's current answer
function checkAnswer(currentLevel) {
  // If the user chose the right color
  if (userClickedPattern[currentLevel] === gamePatterns[currentLevel]) {
    // If the user finished the full sequence correctly
    if (userClickedPattern.length == gamePatterns.length)
      setTimeout(function () {
        nextSequence(); // Move to next level after 1s
      }, 1000);
  } else {
    // Wrong answer: play error sound & show "game over"
    playSound("wrong");
    $("body").addClass("game-over");
    $("#level-title").text("Game Over, Press Any Key to Restart");

    // Remove red background after 200ms
    setTimeout(function () {
      $("body").removeClass("game-over");
    }, 200);

    // Reset game
    startOver();
  }
}

// Function to add press animation effect
function animatePress(currentColor) {
  $("#" + currentColor).addClass("pressed");
  setTimeout(() => {
    $("#" + currentColor).removeClass("pressed");
  }, 100);
}

// Function to play corresponding sound
function playSound(name) {
  let audio = new Audio("sounds/" + name + ".mp3");
  audio.play();
}

// Reset the game
function startOver() {
  gamePatterns = [];
  start = false;
  level = 0;
}
